---
- name: Install Wowza Dependencies
  include_tasks: install-dependencies.yml

- name: Create JKS from ssl certificate and key
  include_tasks: setup-jks.yml

- name: Download Wowza into directory
  include_tasks: download-wowza.yml

- name: Upload post installation tasks to be manually executed after installation wizard
  include_tasks: download-post-install-script.yml